### ISSUE TITLE
в сундуках в адской крепости сундуки с лутом могут лутать только один человек (который их самый первый слутал) и их можно сломать

### ISSUE THREAD

**Issue by DanilKSS** [kitovoi111/ic2classic#16]
**Опишите ошибку**
Четкое и краткое описание ошибки.

**Чтобы воспроизвести**
Шаги для воспроизведения поведения:
1. Перейдите к «...»
2. Нажмите «....»
3. Прокрутите вниз до «....»
4. Посмотрите ошибку

**Ожидаемое поведение**
Четкое и краткое описание того, что вы ожидали.

**Скриншоты**
Если применимо, добавьте скриншоты, чтобы помочь объяснить вашу проблему.

**Comment by kitovoi111** [comment]
Можете ли Вы предоставить скриншоты?

**Comment by kitovoi111** [comment]
Ошибка найдена. Будет исправлено после рестарта.
