### ISSUE TITLE
Биомное лакомство

### ISSUE THREAD

**Issue by ghost** [kitovoi111/ic2classic#41]
**Опишите ошибку**
Биомное лакомство из мода Alex Caves нельзя съесть если голод заполнен хотя он должен привязаться к биому.

**Чтобы воспроизвести**
Шаги для воспроизведения поведения:
1. Получить биомное лакомство
2. Попробовать съесть его с заполненным голодом в любом биоме

**Ожидаемое поведение**
хотел использовать новую механику мода но её нет.

**Скриншоты**
невозможно

**Comment by kitovoi111** [comment]
> **Опишите ошибку** Биомное лакомство из мода Alex Caves нельзя съесть если голод заполнен хотя он должен привязаться к биому.
> 
> **Чтобы воспроизвести** Шаги для воспроизведения поведения:
> 
> 1. Получить биомное лакомство
> 2. Попробовать съесть его с заполненным голодом в любом биоме
> 
> **Ожидаемое поведение** хотел использовать новую механику мода но её нет.
> 
> **Скриншоты** невозможно

Проверьте в 1.20.1 майнкрафте с оригинальным модом эту механику.

**Comment by ghost** [comment]
https://youtu.be/eWhdJ3b60sM?si=gF9F42HVyaA1y79B
в видео с обзором мода на моменте 7:00 можно видеть что оно должно делать
это так же написано на вики по моду https://alexscaves.wiki.gg/wiki/Biome_Treat
в разделе Conversion Crucible
