### ISSUE TITLE
Отсутствие текста и цифр в игре

### ISSUE THREAD

**Issue by skrippik** [kitovoi111/ic2classic#53]
Скачал индустрал крафт и текста вообще не было в игре, пробовал переустановить кристаликс не помогло, помогите пожалуйста

![Uploading 2024-11-23_11.17.25.png…]()
![Uploading 2024-11-23_11.17.13.png…]()
![Uploading 2024-11-23_11.16.36.png…]()

**Comment by kitovoi111** [comment]
Скриншоты не загрузились.
