### ISSUE TITLE
смерть над бедроком

### ISSUE THREAD

**Issue by DanilKSS** [kitovoi111/ic2classic#58]
**Опишите ошибку**
создал портал с помощью пространственного резака в аду, зашёл в него и зашёл в него ещё раз в обычном мире, оказался над бедроком и умер сразу же.

**Чтобы воспроизвести**
Шаги для воспроизведения поведения:
1)зайти в ад
2)создать там портал с помощью пространственного резака
3)зайти в него
4)зайти в него ещё раз в обычном мире
5)умереть над бедроком
6)не иметь возможность забрать ресурсы

**Ожидаемое поведение**
Исправить баг и вернуть вещи

**Скриншоты**
Отката не было

**Comment by kitovoi111** [comment]
Не является ошибкой. Это механика игры.
