### ISSUE TITLE
Баг с жителелями

### ISSUE THREAD

**Issue by fghjjfghjfghj1** [kitovoi111/ic2classic#68]
**Опишите ошибку**
Жители выбирают профессию один раз, и даже если блок их профессии будет уничтожен, профессия останется у жителя.
**Чтобы воспроизвести**
Шаги для воспроизведения поведения:
1. Перейдите к «жители без профессии »
2. поставьте «блок профессии »
3. уничтожьте блок профессии после взятия профессии «....»
4. Посмотрите ошибку

**Ожидаемое поведение**
При уничтожении блока профессии должна исчезать и сама профессия.
**Скриншоты**
Если применимо, добавьте скриншоты, чтобы помочь объяснить вашу проблему.

**Comment by kitovoi111** [comment]
Не является ошибкой. Это механика от прокрута профессии жителей.
